name: Deploy Application

on: 
  workflow_run: 
    workflows: ["Build and Push Admin FE Docker Image", "Build and Push Admin BE Docker Image"]
    types: 
      - completed

jobs:
  deploy:
    name: Deploy Application
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Deploy FE
        run: |
          pwd && ls
          cd deployments/fe
          docker-compose down
          docker-compose pull
          docker-compose up -d

      - name: Deploy BE
        run: |
          cd deployments/be
          docker-compose down
          docker-compose pull
          docker-compose up -d

